version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ISC_DATA_DIRECTORY: /external/IRISHEALTH
    ports: 
      - 1972
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - key_external:/external
volumes:
  key_external: {}